export type PatchNote = {
  date: string;
  id: string;
  items: string[];
  title: string;
  type: "fix" | "feature" | "system";
  version: string;
};

// Jede produktive Aenderung bekommt hier ab jetzt einen Eintrag.
export const patchNotes: PatchNote[] = [
  {
    date: "20.06.2026",
    id: "discord-ticket-delete-button-no-hang",
    items: [
      "Ticket loeschen antwortet jetzt sofort sichtbar statt bei der Transkript-Sicherung auf Discords Denkt nach stehen zu bleiben.",
      "Transkript-Erstellung und Channel-Loeschen haben Timeouts; wenn das Transkript nicht sicher gespeichert wird, bleibt der Kanal erhalten.",
      "Fehler beim Loeschen werden als Ticket-Log protokolliert und dem ausloesenden Admin direkt angezeigt.",
    ],
    title: "Ticket-Loeschen haengt nicht mehr",
    type: "fix",
    version: "0.10.37",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-close-transcript-delete-actions",
    items: [
      "Nach dem Schliessen eines Tickets wird die Ticket-Bedienung auf Transkript erstellen und Ticket loeschen umgestellt.",
      "Ticket loeschen sichert vorher nochmal ein Transkript und entfernt danach den Discord-Ticketchannel.",
      "Die Fallakte, Logs und gespeicherten Belege bleiben erhalten; geloescht wird nur der Discord-Kanal.",
    ],
    title: "Ticket-Abschlussaktionen",
    type: "feature",
    version: "0.10.36",
  },
  {
    date: "20.06.2026",
    id: "sanctions-advisor-file-url-evidence-analysis",
    items: [
      "KI-Sanktionsberater haengt hochgeladene Supabase-Belege jetzt als OpenAI input_image oder input_file an die Auswertung an.",
      "Bilder, PDFs, Office-/LibreOffice-Dokumente, Praesentationen, Tabellen, Text-/Webdateien und passende Datei-URLs koennen dadurch inhaltlich bewertet werden.",
      "Normale oeffentliche Webseiten-URLs werden als Textauszug beigelegt; abgelaufene oder nicht oeffentlich lesbare Links fuehren zu konservativer manueller Pruefung statt hartem Fehler.",
    ],
    title: "Belege werden wirklich ausgewertet",
    type: "feature",
    version: "0.10.35",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-user-id-and-voice-channel-select",
    items: [
      "Ticketflow hat jetzt Discord-ID-Fallbacks fuer Gegenpartei, Ausschluss und Person hinzufuegen, falls Discords User-Suche Mitglieder nicht findet.",
      "Mehrere Discord-IDs oder @Mentions koennen per Zeile oder Komma eingetragen werden.",
      "Ort-Auswahl zeigt jetzt auch Sprachkanaele und Stage-Kanaele an.",
    ],
    title: "Ticket-Suche und Ort-Auswahl erweitert",
    type: "fix",
    version: "0.10.34",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-create-bitfield-fix",
    items: [
      "Ticketchannel-Erstellung uebergibt User-Rechte beim initialen Discord-Channel-Create jetzt als Bitfield-kompatible Permission-Liste.",
      "Damit ist der konkrete Discord.js-Fehler BitFieldInvalid: Invalid bitfield flag or number behoben.",
      "Die spaeteren Person-hinzufuegen-Rechte bleiben unveraendert und werden weiterhin bewusst per Button gesetzt.",
    ],
    title: "Ticketchannel-Bitfieldfehler behoben",
    type: "fix",
    version: "0.10.33",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-counterpart-access-revert",
    items: [
      "Gegenparteien werden beim Ticket-Erstellen nicht mehr automatisch dem privaten Ticketchannel hinzugefuegt.",
      "Automatischer Channelzugriff gilt nur fuer den Ersteller und den Bot; weitere Personen muessen bewusst ueber Person hinzufuegen eingeladen werden.",
      "Die Gegenpartei bleibt weiter als Fallbezug im Ticket gespeichert, ohne dadurch Zugriff auf Belege oder interne Unterhaltung zu erhalten.",
    ],
    title: "Gegenpartei bleibt ohne Auto-Zugriff",
    type: "fix",
    version: "0.10.32",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-overwrite-fallback",
    items: [
      "Ticketchannel wird jetzt zuerst mit minimalen Benutzerrechten erstellt; Rollenrechte werden danach einzeln gesetzt.",
      "Wenn eine Discord-Rolle wegen Hierarchie oder fehlender Bot-Rechte blockiert, scheitert nicht mehr die komplette Ticket-Erstellung.",
      "Exakte Discord-Fehler aus der Channel-Erstellung und Rollenrechte-Vergabe werden ab jetzt in den Ticket-Logs gespeichert.",
    ],
    title: "Ticket-Rechte robuster gesetzt",
    type: "fix",
    version: "0.10.31",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-channel-create-repair",
    items: [
      "Ticket-Erstellung filtert ungueltige Discord-Rollen vor dem Channel-Anlegen heraus.",
      "Gegenparteien bekommen beim Sofortticket jetzt direkten Zugriff auf den Ticketchannel, sofern sie nicht explizit ausgeschlossen wurden.",
      "Wenn Discord den Channel trotzdem ablehnt, wird das Supabase-Ticket automatisch abgebrochen statt als offenes Phantom ohne Channel liegen zu bleiben.",
      "Discord zeigt bei Ticketfehlern jetzt eine konkretere Kurzdiagnose fuer Supabase-Cache, offene Ticketgrenze oder fehlende Bot-Rechte.",
    ],
    title: "Ticketchannel-Erstellung abgesichert",
    type: "fix",
    version: "0.10.30",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-details-modal-removal",
    items: [
      "Ticket-Erstellung nutzt nach der Zeit-Auswahl kein Discord-Modal mehr, sondern ein Auswahlfeld Worum geht es grob?.",
      "Der Ticketchannel wird danach sofort erstellt; Details werden direkt im Channel geschrieben und automatisch als Beleg gespeichert.",
      "Auch alte Details-eingeben-Buttons laufen nun in einen Sofortabschluss statt erneut in den fehlerhaften Modalpfad.",
    ],
    title: "Ticket-Details ohne Modal",
    type: "fix",
    version: "0.10.29",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-time-step-button-repair",
    items: [
      "Zeit-Auswahl im Ticketflow oeffnet nicht mehr direkt ein Discord-Modal aus dem Select-Menue.",
      "Nach Heute/Gestern/Gerade eben erscheint jetzt ein Button Details eingeben; bei genauer Zeit ein Button Zeit und Details eingeben.",
      "Damit wird der Discord-Fehler nach der Auswahl Gestern vermieden und der Ticketflow bleibt klickbar.",
    ],
    title: "Ticket-Zeitschritt repariert",
    type: "fix",
    version: "0.10.28",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-button-interface",
    items: [
      "Ticketpanel hat jetzt direkte Buttons fuer Ticket erstellen, Anleitung und Setup reparieren.",
      "Ticket-Channels haben einen Person-hinzufuegen-Button mit Discord-User-Auswahl, damit Admins nicht mehr /add oder !add tippen muessen.",
      "Setup- und Anleitungstexte wurden bereinigt, sodass Discord keine kaputten @User-Platzhalter oder Markdown-Links in die Antwort zieht.",
    ],
    title: "Ticket-Interface vereinfacht",
    type: "feature",
    version: "0.10.27",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-text-command-fallbacks",
    items: [
      "Ticket-System kann jetzt auch ohne Discord-Slash-Liste per Textbefehl bedient werden: !ticket-setup, !ticket-anleitung und !add @User Grund.",
      "Text-Fallbacks nutzen dieselben Rechtepruefungen wie die Slash-Commands und speichern Ticketbelege nicht versehentlich als normale Evidence.",
      "README und Bot-Env-Beispiel dokumentieren den neuen DISCORD_TEXT_COMMAND_PREFIX.",
    ],
    title: "Ticket-Textbefehle ergaenzt",
    type: "fix",
    version: "0.10.26",
  },
  {
    date: "20.06.2026",
    id: "discord-ticket-setup-and-image-submit-repair",
    items: [
      "Discord-Bot registriert Ticket-Slash-Commands beim Start automatisch und legt Ticketpanel, Ticket-Log, Bilder-Protokoll sowie Kategorie idempotent an.",
      "Neue Discord-Arbeitsanweisung per /ticket-anleitung ergaenzt; /ticket-setup und /add sind nicht mehr durch Discord-ManageGuild-Permissions versteckt.",
      "Mitgliederaktenbild-DMs akzeptieren jetzt auch Discord-Anhaenge mit fehlendem oder generischem Content-Type, solange Dateiname oder URL ein Bildformat erkennen lassen.",
    ],
    title: "Ticket-System und Aktenbilder repariert",
    type: "fix",
    version: "0.10.25",
  },
  {
    date: "18.06.2026",
    id: "patchnotes-overlay-z-index-repair",
    items: [
      "Patchnotes-Dialog bleibt jetzt trotz temporaerer Event-Designs als echtes Overlay sichtbar.",
      "Die Design-Schale ueberschreibt modale Layer nicht mehr auf normales Seitenlayout.",
      "Lockdown-Hinweis nutzt dieselbe Overlay-Schutzklasse, damit er ebenfalls nicht vom Theme-Z-Index geschluckt wird.",
    ],
    title: "Patchnotes-Overlay repariert",
    type: "fix",
    version: "0.10.24",
  },
  {
    date: "18.06.2026",
    id: "patchnotes-button-openai-model-status",
    items: [
      "Patchnotes sind in der Topbar wieder als klarer Button mit Beschriftung und Versions-Badge sichtbar.",
      "Der Patchnotes-Dialog zeigt die aktuelle Version im Kopfbereich und hat einen sichtbaren Schliessen-Button.",
      "OPENAI_MODEL wird nicht mehr faelschlich als Fehler markiert, wenn das serverseitige Standardmodell genutzt wird.",
    ],
    title: "Patchnotes-Button und OpenAI-Status repariert",
    type: "fix",
    version: "0.10.23",
  },
  {
    date: "18.06.2026",
    id: "temporary-design-storage-animation-repair",
    items: [
      "Neue Supabase-Reparaturmigration fuer temporaere Designs angelegt: Tabellen, RLS, Data-API-GRANTs, Rechte und alle Vorlagen werden idempotent synchronisiert.",
      "Der Statushinweis nennt jetzt die konkrete Migration, wenn Supabase die Design-Tabellen oder Rechte noch nicht kennt.",
      "Alle Event-Vorlagen zeigen jetzt in Live-Seiten und Vorschau eigene animierte Motive statt nur Farbwechsel.",
    ],
    title: "Design-Speicher und Animationen repariert",
    type: "fix",
    version: "0.10.22",
  },
  {
    date: "18.06.2026",
    id: "wm-2026-preview-animation-parity",
    items: [
      "Die WM-Vorschau zeigt jetzt ebenfalls die neuen Spielfeldlinien, Flutlichter, Konfetti-Elemente und die animierte Schwarz-Rot-Gold-Bannerleiste.",
      "Live-Overlay und Design-Vorschau sind dadurch visuell konsistenter; neue WM-Effekte sind vor dem Speichern direkt erkennbar.",
    ],
    title: "WM-Vorschau an Live-Overlay angepasst",
    type: "fix",
    version: "0.10.21",
  },
  {
    date: "18.06.2026",
    id: "wm-2026-overlay-animation-boost",
    items: [
      "Das WM-Overlay wurde bewusst auffaelliger animiert: mehr Fussbaelle, mehr Bewegung und mehr sichtbare Stadion-Action.",
      "Neue Konfetti- und Flutlicht-Layer laufen nur im WM-Design und respektieren Reduced-Motion.",
      "Die WM-Vorschau zeigt jetzt ebenfalls mehr animierte Elemente, damit das Design vor dem Speichern nicht mehr tot wirkt.",
    ],
    title: "WM-Animationen aufgedreht",
    type: "feature",
    version: "0.10.20",
  },
  {
    date: "18.06.2026",
    id: "wm-2026-overlay-redesign",
    items: [
      "Das WM-Design nutzt jetzt konsequent Schwarz-Rot-Gold; der gruene Bannerblock wurde entfernt.",
      "Die WM-Atmosphaere zeigt groessere animierte Fussbaelle, bewegte Deutschland-Baender und Flutlicht-Effekte statt kaum sichtbarer Hintergrundpunkte.",
      "Die WM-Vorlage wurde auf die neuen Farben umgestellt, damit Vorschau und gespeicherte Designs nicht wieder in den gruenen Feld-Look kippen.",
    ],
    title: "WM-Overlay nachgeschaerft",
    type: "feature",
    version: "0.10.19",
  },
  {
    date: "17.06.2026",
    id: "temporary-design-event-overlays",
    items: [
      "Event-Designs haben jetzt eigene animierte Atmosphaeren-Layer mit mehreren Motivteilen statt nur dezenter Farbverlaeufe.",
      "WM, Weihnachten, Ostern, Neujahr, Halloween, Valentinstag, Frauentag, Maennertag und Black Friday wirken in Live-App und Vorschau deutlich eigenstaendiger.",
      "Die Vorschau in den Design-Einstellungen zeigt die neuen animierten Motive direkt mit an und respektiert Reduced-Motion.",
    ],
    title: "Event-Overlays ueberarbeitet",
    type: "feature",
    version: "0.10.18",
  },
  {
    date: "17.06.2026",
    id: "discord-age-role-sync",
    items: [
      "Der Discord-Bot vergibt nach dem normalen Mitgliederaktenbogen automatisch genau eine passende Altersrolle fuer 14+, 16+, 18+ oder 20+.",
      "Falsche Altersrollen aus der Vierer-Staffel werden entfernt, andere Discord-Rollen bleiben unveraendert.",
      "Fehlende Rollen, Berechtigungsprobleme und deaktivierte Synchronisation werden nachvollziehbar im Bot und in den Mitgliederakten-Logs protokolliert.",
    ],
    title: "Altersrollen aus Aktenbogen",
    type: "feature",
    version: "0.10.17",
  },
  {
    date: "17.06.2026",
    id: "discord-ticket-member-image-system",
    items: [
      "Discord-Tickets koennen ueber ein Bot-Panel erstellt, privat protokolliert und mit Evidence/Transcript in Supabase gespeichert werden.",
      "Der KI-Sanktionsberater ist in Tickets angebunden, bleibt aber ausdruecklich nur Beratung; Sanktionen laufen weiter ueber berechtigte Admin-Aktionen.",
      "Neue Mitglieder werden nach 4 Stunden per DM nach genau einem Mitgliederaktenbild gefragt; gueltige Bilder werden als Profilbild der Akte gespeichert und Fristverstoesse landen in der Moderationsqueue.",
    ],
    title: "Discord Ticket-System",
    type: "feature",
    version: "0.10.16",
  },
  {
    date: "17.06.2026",
    id: "temporary-design-rich-skins",
    items: [
      "Design-Vorlagen sind jetzt echte Skins mit saisonalen Hintergrundornamenten, Banner-Emblemen, Mini-Vorschau und Button-Akzenten.",
      "Vorlagen speichern Motiv und Kopfstil in Supabase mit, damit Bearbeiten nicht mehr auf reine Farbaenderungen zurueckfaellt.",
      "Die Vorschau ist sauber in die Einstellungsseite eingebettet und erzeugt keine Vollbild-Overlays mehr ausserhalb der Live-App-Schale.",
    ],
    title: "Design-Vorlagen als Skins",
    type: "feature",
    version: "0.10.15",
  },
  {
    date: "17.06.2026",
    id: "world-cup-2026-design",
    items: [
      "WM-2026-Design fertig vorkonfiguriert: Zeitraum 11.06.2026 bis 19.07.2026, hohe Prioritaet und automatische Aktivierung.",
      "Theme nutzt Spielfeld-Hintergrund, WM-Banner und Gruen/Gold/Rot-Akzente fuer eine fertige Turnieroptik.",
      "Supabase-Migration aktualisiert auch bereits vorhandene alte WM-Vorlagen, statt nur neue Installationen zu befuellen.",
    ],
    title: "WM 2026 Design",
    type: "feature",
    version: "0.10.14",
  },
  {
    date: "17.06.2026",
    id: "temporary-design-admin-repair",
    items: [
      "Design-Einstellungen neu geordnet: Status, Vorschau, Aktivierung und Vorlagenbearbeitung sind getrennte Bereiche.",
      "Vorschau hat jetzt einen expliziten Button und eine eigene Mini-Ansicht, damit Theme-Wechsel sofort sichtbar sind.",
      "Supabase-Anbindung fuer temporaere Designs schreibt serverseitig robuster und bringt eine idempotente Reparatur-Migration mit.",
    ],
    title: "Temporaere Designs repariert",
    type: "fix",
    version: "0.10.13",
  },
  {
    date: "15.06.2026",
    id: "temporary-design-system",
    items: [
      "Neues Feature Temporaere Designs mit automatischer Datumslogik, manueller Aktivierung und Admin-Vorschau ergaenzt.",
      "Design-Vorlagen fuer Frauentag, Maennertag, WM 2026, Weihnachten, Ostern, Neujahr, Halloween, Valentinstag und Black Friday vorbereitet.",
      "Designs aendern ausschliesslich visuelle Variablen, Banner und Theme-Klassen; Funktionen und Datenablaeufe bleiben unveraendert.",
    ],
    title: "Temporaere Designs",
    type: "feature",
    version: "0.10.12",
  },
  {
    date: "15.06.2026",
    id: "ai-sanction-advice-direct-storage-upload",
    items: [
      "KI-Sanktionsberater laedt Belegdateien jetzt vor dem Absenden direkt zu Supabase Storage hoch.",
      "Der Button-Post enthaelt nur noch kleine Metadaten, damit Vercels Upload-Grenze keine Fehlerseite mehr ausloest.",
      "Die Beratung uebernimmt die hochgeladenen Belege danach serverseitig in die Fallakte und kann direkt ausgewertet werden.",
    ],
    title: "Beratungs-Uploads ohne Fehlerseite",
    type: "fix",
    version: "0.10.11",
  },
  {
    date: "15.06.2026",
    id: "ai-sanction-advice-upload-count-20",
    items: [
      "KI-Sanktionsberater erlaubt jetzt bis zu 20 Belegdateien pro Beratung.",
      "Die Schutzgrenzen fuer 20 MB pro Datei und 45 MB Gesamtgroesse bleiben aktiv, damit Uploads kontrolliert abgefangen werden.",
    ],
    title: "Mehr Beratungs-Belege",
    type: "fix",
    version: "0.10.10",
  },
  {
    date: "14.06.2026",
    id: "ai-sanction-advice-upload-guard",
    items: [
      "KI-Sanktionsberater prueft Belegdateien jetzt vor dem Absenden direkt im Formular.",
      "Zu viele, zu grosse oder insgesamt zu schwere Uploads blockieren die Buttons mit lesbarer Meldung statt einer schwarzen Next-Fehlerseite.",
      "Serverseitig gibt es eine eigene Meldung fuer Beratungs-Uploads ueber 45 MB Gesamtgroesse.",
    ],
    title: "Beratungs-Uploads abgefangen",
    type: "fix",
    version: "0.10.9",
  },
  {
    date: "14.06.2026",
    id: "ai-sanction-advice-stability",
    items: [
      "KI-Sanktionsberater faellt bei langsamer oder fehlgeschlagener OpenAI-Antwort kontrolliert auf manuelle Pruefung zurueck.",
      "Auswertung bricht nicht mehr hart ab, wenn Belege, Zielperson, alte Warns/Bans/Kicks oder Regelwerksdaten beim Vorab-Laden Probleme machen.",
      "OpenAI-Aufruf nutzt ein Antwortlimit, niedrigen Reasoning-Aufwand und ein serverseitiges Zeitlimit fuer stabilere Production-Auswertungen.",
      "Interne Fehlertexte werden bereinigt, damit keine API-Key-Fragmente in Beratungsakten oder Protokolle geschrieben werden.",
    ],
    title: "KI-Sanktionsberater stabilisiert",
    type: "fix",
    version: "0.10.8",
  },
  {
    date: "13.06.2026",
    id: "google-drive-file-sync",
    items: [
      "Datei- und Ordnerverwaltung speichert Google-Drive-IDs als feste Verknuepfung.",
      "Manueller Google-Drive-Sync, sichere Sync-Laeufe, Protokolle und Konfliktanzeige wurden ergaenzt.",
      "Uploads koennen mehrere Dateien annehmen und werden nach Drive in den passenden Ordner gespiegelt.",
      "Ordner-Uploads behalten relative Unterordner bei, sofern der Browser diese Pfade mitsendet.",
      "Google-Docs-Dokumente koennen aus der festgelegten Vorlage erstellt und als Vorschau geoeffnet werden.",
      "Loeschen markiert Dateien nur noch sicher als geprueftes Soft-Delete statt Storage oder Drive direkt zu entfernen.",
      "Automatische Drive-Sync-Cronjobs laufen exakt fuer 06:00 und 20:00 Uhr Europe/Berlin mit Sommer-/Winterzeit-Pruefung.",
      "Die Dateiuebersicht bleibt auch vor eingespielter Drive-Migration im alten Datenbankschema sichtbar.",
      "Grosse Drive-Ordner werden in fortsetzbaren Portionen synchronisiert und fehlende Drive-Schreibrechte blockieren den Import nicht mehr.",
      "Teilweise Drive-Syncs werden im Hinweisbereich korrekt als Teil-Erfolg angezeigt und Konflikte bekommen lesbare Bezeichnungen.",
    ],
    title: "Google Drive Datei-Sync",
    type: "feature",
    version: "0.10.7",
  },
  {
    date: "13.06.2026",
    id: "representation-approval-dm-flow",
    items: [
      "Amtsvertretungen werden vor der Rollenzuweisung per Discord-DM bei der vertretenden Person angefragt.",
      "Die DM enthaelt Zeitraum, zu vertretende Person, Funktion, Grund und Zustimmen/Ablehnen-Buttons.",
      "Bei Zustimmung setzt der Bot die Vertretungsrolle wie bisher automatisch.",
      "Bei Ablehnung oder nicht zustellbarer DM sucht die Verwaltung automatisch die naechste freie Vertretung.",
    ],
    title: "Zustimmung fuer Amtsvertretung",
    type: "feature",
    version: "0.10.6",
  },
  {
    date: "13.06.2026",
    id: "root-two-factor-requirement-control",
    items: [
      "Root Owner koennen die 2FA-Pflicht fuer Website-Benutzer gezielt deaktivieren oder wieder erzwingen.",
      "Benutzer mit deaktivierter 2FA-Pflicht erhalten nach dem Login vollen Zugriff gemaess Rollenrechten.",
      "Benutzerverwaltung zeigt 2FA-Einrichtung und 2FA-Pflicht getrennt an.",
      "Aenderungen an der 2FA-Pflicht werden serverseitig geprueft und protokolliert.",
    ],
    title: "Root-Steuerung fuer 2FA-Pflicht",
    type: "feature",
    version: "0.10.5",
  },
  {
    date: "12.06.2026",
    id: "discord-absence-representations",
    items: [
      "Neue Ansicht Amtsvertretung fuer Abmeldungen, Amtsrollen und Vertretungsberechtigungen.",
      "Abmeldungen legen automatisch Bot-Auftraege fuer passende Discord-Amtsrollen an.",
      "Der Discord-Bot setzt Vertretungsrollen temporaer und entfernt sie beim Beenden nur, wenn sie automatisch vergeben wurden.",
      "Benachrichtigungen zeigen offene oder fehlgeschlagene Vertretungsauftraege im Panel an.",
    ],
    title: "Abmeldung mit Amtsvertretung",
    type: "feature",
    version: "0.10.4",
  },
  {
    date: "12.06.2026",
    id: "discord-member-intake-split-fields",
    items: [
      "Discord-Aktenbogen nutzt jetzt einzelne Formularteile fuer Basisdaten, Socials und Gaming.",
      "Instagram, Snapchat, TikTok, Stream, Ubisoft und EA werden als eigene Felder gespeichert.",
      "Die Massenausgabe bleibt gesperrt, bis Test-Empfaenger oder Bulk-Freigabe explizit gesetzt sind.",
      "Alte Sammelfeld-Aktenbogen werden durch die neue Formularversion erneut als offen erkannt.",
    ],
    title: "Aktenbogen mit Einzelfeldern",
    type: "fix",
    version: "0.10.3",
  },
  {
    date: "11.06.2026",
    id: "discord-member-intake-questionnaire",
    items: [
      "Discord-Bot verschickt Mitgliedern einen Aktenbogen per DM mit Discord-Formular.",
      "Neue Mitglieder werden erst nach 3 Stunden automatisch angeschrieben.",
      "Eingereichte Antworten werden in die Mitgliederakte uebernommen und im Aktenkopf zur Pruefung angezeigt.",
      "Die angegebenen Ausnahme-Discord-IDs werden bei der einmaligen Anfrage an bestehende Mitglieder uebersprungen.",
    ],
    title: "Discord-Aktenbogen",
    type: "feature",
    version: "0.10.2",
  },
  {
    date: "11.06.2026",
    id: "member-record-profile-images",
    items: [
      "Mitgliederakten koennen jetzt direkt im Aktenkopf ein Profilbild anzeigen.",
      "Profilbilder lassen sich aus der geoeffneten Akte hochladen und werden automatisch als Profilbild-Dateiverknuepfung gesetzt.",
      "Beim Setzen eines neuen Profilbilds wird die aktive Profilbildreferenz der Akte aktualisiert.",
    ],
    title: "Profilbilder fuer Akten",
    type: "feature",
    version: "0.10.1",
  },
  {
    date: "10.06.2026",
    id: "discord-member-fetch-backoff",
    items: [
      "Discord-Bot cached den kompletten Member-Fetch, damit Lockdown nicht mehrfach Gateway Opcode 8 ausloest.",
      "Opcode-8-Rate-Limits werden mit Discord-Retry-Zeit abgewartet, statt als Lockdown-Fehler im Protokoll zu landen.",
      "Beim Bot-Start wird die Lockdown-Queue vor dem grossen Vollabgleich verarbeitet.",
    ],
    title: "Discord Member-Fetch gedrosselt",
    type: "fix",
    version: "0.9.18",
  },
  {
    date: "10.06.2026",
    id: "lockdown-dm-delivery-guard",
    items: [
      "Lockdown bricht vor jeder Discord-Rechteaenderung ab, wenn kein Notfallschluessel per DM zugestellt wurde.",
      "Bei fehlgeschlagener Lockdown-Aktivierung wird der Web-Lockdown automatisch wieder deaktiviert.",
      "Nicht zugestellte Notfallschluessel werden aus der Bot-Queue entfernt und im Protokoll mit Empfaengerstatus gespeichert.",
    ],
    title: "Lockdown nur mit zugestellter DM",
    type: "fix",
    version: "0.9.17",
  },
  {
    date: "10.06.2026",
    id: "discord-bot-boot-check",
    items: [
      "Discord-Bot startet wieder: Lockdown-Konstanten werden vor der Konfiguration initialisiert.",
      "Bot-Check fuehrt jetzt einen echten Boot-Smoke-Test aus, damit Runtime-Startfehler vor Railway auffallen.",
      "Der Boot-Test laeuft ohne Discord-Login, prueft aber die komplette Modulinitialisierung.",
      "Schneller Legacy-Restore erhaelt vorhandene Rechte-Bits, die im alten Snapshot nicht enthalten waren.",
    ],
    title: "Bot-Startfehler behoben",
    type: "fix",
    version: "0.9.16",
  },
  {
    date: "10.06.2026",
    id: "lockdown-bot-heartbeat-guard",
    items: [
      "Lockdown-Aktivierung wird jetzt in Supabase blockiert, wenn der Discord-Bot laenger als 2 Minuten kein Live-Signal gesendet hat.",
      "Offline-Bot-Lockdowns werden nicht mehr angelegt, damit kein Notfallschluessel ohne Discord-DM-Zustellung entsteht.",
      "Bot-Start ist robuster: Heartbeat und Lockdown-Restore laufen weiter, auch wenn ein Startup-Sync fehlschlaegt.",
      "Die Oberflaeche zeigt fuer diesen Fall eine eigene Bot-offline-Meldung statt einer allgemeinen Fehlermeldung.",
    ],
    title: "Lockdown gegen Bot-Ausfall gesichert",
    type: "fix",
    version: "0.9.15",
  },
  {
    date: "10.06.2026",
    id: "lockdown-role-quarantine",
    items: [
      "Discord-Lockdown nutzt fuer neue Aktivierungen einen schnellen Rollen-Quarantaene-Modus statt tausender Channel/Rollen-Overwrites.",
      "Nicht-Admin-Mitglieder bekommen temporaer eine Lockdown-Rolle, normale verwaltbare Rollen werden im Snapshot geparkt und beim Entsperren wiederhergestellt.",
      "Wichtige Channels bleiben nur lesbar, alle anderen Channels werden fuer die Lockdown-Rolle dicht gemacht.",
      "Bestehende mitgliederspezifische Channel-Overwrites werden mitgesichert und waehrend des Lockdowns ebenfalls hart eingeschraenkt.",
      "Lockdown sperrt jetzt auch typische Kanal-, Thread-, Webhook-, Invite- und Message-Management-Rechte.",
      "Alte grosse Lockdown-Snapshots werden beim Restore kanalweise wiederhergestellt, damit der Rueckbau nicht mehr tausende Einzelaktionen braucht.",
      "Alte Lockdown-Snapshots bleiben kompatibel, damit vorhandene Restore-Laeufe weiter funktionieren.",
    ],
    title: "Lockdown schneller und haerter",
    type: "fix",
    version: "0.9.14",
  },
  {
    date: "10.06.2026",
    id: "lockdown-dm-before-channel-lock",
    items: [
      "Lockdown-Notfallschluessel wird jetzt direkt nach Snapshot-Sicherung per DM verschickt.",
      "Discord-Channel-Sperren starten erst nach dem DM-Versand, damit Rate-Limits den Notfallschluessel nicht verzoegern.",
      "Bot-API gibt vorhandene Pre-Lockdown-Snapshots auch fuer Aktivierungsbefehle weiter.",
    ],
    title: "Lockdown-DM vor Sperre",
    type: "fix",
    version: "0.9.13",
  },
  {
    date: "10.06.2026",
    id: "discord-server-snapshot",
    items: [
      "Discord-Bot kann einen aktuellen Server-Snapshot ohne Rechteaenderung erfassen.",
      "Snapshot enthaelt Rollen, Channel, Channel-Overwrites und Member-Rollenzuordnung.",
      "Snapshot wird als Bot-Befehl mit Summary und Rohdaten in Supabase gespeichert.",
    ],
    title: "Discord-Server-Snapshot",
    type: "system",
    version: "0.9.12",
  },
  {
    date: "10.06.2026",
    id: "discord-audit-lockdown-permission-restore",
    items: [
      "Discord-Bot kann Channel-Overwrite-Audit-Logs fuer ein Zeitfenster auslesen.",
      "Audit-Restore stellt serverweite Channel-Berechtigungen anhand des fruehesten Vorher-Zustands im Lockdown-Zeitfenster wieder her.",
      "Restore laeuft gedrosselt gegen Discord, damit Rate-Limits nicht erneut den Reparaturlauf zerlegen.",
      "Discord-429-Antworten werden automatisch mit Backoff erneut versucht.",
      "Bereits geloeschte Overwrites werden beim Wiederholungslauf als erledigt behandelt.",
      "Rohes Discord-Audit-Log wird jetzt mit old_value/new_value gelesen, damit Update/Delete-Overwrites nicht uebersprungen werden.",
      "Unvollstaendige Audit-Bitsets werden aus aktuellem Overwrite oder 0 ergaenzt, damit @everyone-Restfaelle wiederhergestellt werden koennen.",
      "Lockdown-Bot-API reicht Reparaturmodus und Zeitfenster an den Railway-Bot durch.",
    ],
    title: "Discord-Rechte per Audit-Log reparieren",
    type: "fix",
    version: "0.9.11",
  },
  {
    date: "10.06.2026",
    id: "lockdown-snapshot-fallback-restore",
    items: [
      "Discord-Bot bricht beim Lockdown-Beenden nicht mehr ab, wenn kein Snapshot gespeichert wurde.",
      "Ohne Snapshot entfernt der Bot gezielt erkannte Lockdown-Sperren von Nicht-Admin-Rollen.",
      "Lockdown-Aktivierung speichert Rechte jetzt vor der Notfall-DM-Aufloesung, damit Discord-Rate-Limits keinen fehlenden Snapshot mehr verursachen.",
      "Fehler beim Senden oder Aufloesen der Notfall-DMs werden protokolliert, blockieren aber nicht mehr den Rechte-Snapshot.",
      "Notfall-Reparatur arbeitet mit einer stabilen Overwrite-Liste, damit Discord-Cache-Aenderungen den Restore nicht festhaengen.",
    ],
    title: "Lockdown-Restore abgesichert",
    type: "fix",
    version: "0.9.10",
  },
  {
    date: "10.06.2026",
    id: "lockdown-login-emergency-gate",
    items: [
      "Login-Seite bekommt bei aktivem Lockdown einen vollflaechigen Notfall-Sperrbildschirm.",
      "Lockdown-Sperrbildschirm verdeckt den normalen Login, bis der Notfallschluessel eingetragen wurde.",
      "Emergency-Sound startet automatisch soweit der Browser es erlaubt und faellt auf erste Eingabe zurueck.",
      "Lockdown kann im aktiven Zustand auch mit Notfallschluessel beendet werden, falls 2FA gerade blockiert.",
      "Beim Beenden bleibt der Discord-Restore-Befehl erhalten, damit der Bot alte Channel-Rechte wiederherstellt.",
    ],
    title: "Lockdown-Sperrbildschirm",
    type: "feature",
    version: "0.9.9",
  },
  {
    date: "10.06.2026",
    id: "lockdown-ui-recipient-select",
    items: [
      "Lockdown-Overlay deutlich kompakter und weniger stoerend gestaltet.",
      "Lockdown-Panel optisch aufgeraeumt und Statuskarten beruhigt.",
      "Notfallschluessel-Empfaenger koennen jetzt aus verknuepften Mitgliedern ausgewaehlt werden, statt Discord-IDs per Hand einzutragen.",
      "Lockdown-Felder haben eigene Kontrastklassen, damit Eingaben und Mitgliedernamen sichtbar bleiben.",
      "losoverdrive bleibt als Sicherheits-Empfaenger fuer Lockdown-DMs hinterlegt.",
    ],
    title: "Lockdown-UI bereinigt",
    type: "fix",
    version: "0.9.8",
  },
  {
    date: "10.06.2026",
    id: "drive-import-lockdown",
    items: [
      "Google-Drive-Dokumente als geordnete Datei-Datenbank-Eintraege importiert und Kategorien fuer Kommunikation, Ermittlungen, Gesetzgebung, Verwaltung, Sonderbereiche und Ungeordnet angelegt.",
      "Externe Drive-Dateien koennen ueber die vorhandene geschuetzte Oeffnen-Logik direkt geoeffnet werden.",
      "Roten Lockdown-Bereich in den Einstellungen mit animiertem Emergency-Overlay und optionalem Alarmton ergaenzt.",
      "Lockdown sperrt Webzugriff ueber Notfallschluessel und queued Discord-Befehle fuer den Railway-Bot.",
      "Discord-Bot kann Nicht-Admin-Rollen kanalweit sperren, wichtige Channels lesbar lassen, Notfallcodes per DM senden und Rechte beim Entsperren wiederherstellen.",
      "Supabase Advisor-Funde fuer Lockdown-Funktionen nachgehaertet: keine anonyme Ausfuehrung und neue FK-Indizes.",
    ],
    title: "Drive-Import und Lockdown",
    type: "feature",
    version: "0.9.7",
  },
  {
    date: "10.06.2026",
    id: "roles-permissions-restructure",
    items: [
      "Neue Zielstruktur fuer Rollen und Berechtigungen als additive Migration vorbereitet.",
      "Root Owner und Platform Admin werden getrennt und in der Benutzerverwaltung geschuetzt.",
      "Legacy-Administrator wird in der Migration auf Root Owner und Platform Admin migriert.",
      "Legacy-Administrator wird vor Anlage des neuen Platform Admin umbenannt, damit der eindeutige Rollenname nicht kollidiert.",
      "Neue Permission-Gruppen fuer Akten, Ermittlungen, Kommunikation, Audit und Ordnerrechte ergaenzt.",
      "Erststart- und Rollenmeldungen wurden auf Root Owner / Administrator angepasst.",
    ],
    title: "Rollenstruktur vorbereitet",
    type: "system",
    version: "0.9.6",
  },
  {
    date: "10.06.2026",
    id: "hardware-key-mfa",
    items: [
      "Hardware-Key/WebAuthn als zweite 2FA-Methode ergaenzt.",
      "QR/TOTP bleibt bestehen, Nutzer koennen Code oder Key verwenden.",
      "Die 2FA-Seite zeigt klare Hinweise, wenn Browser oder Supabase-Projekt WebAuthn noch nicht zulassen.",
    ],
    title: "Hardware-Key fuer 2FA",
    type: "feature",
    version: "0.9.5",
  },
  {
    date: "10.06.2026",
    id: "session-countdown-timer",
    items: [
      "Oben rechts zeigt jetzt ein Timer die verbleibende Login-Sitzung.",
      "Die Anzeige wechselt vor Ablauf auf Warnfarbe.",
      "Bei Ablauf wird die Seite aktualisiert, damit der erneute Login sofort greift.",
    ],
    title: "Session-Timer sichtbar",
    type: "feature",
    version: "0.9.4",
  },
  {
    date: "09.06.2026",
    id: "auth-session-timebox",
    items: [
      "Anmeldesitzungen laufen jetzt hart nach 45 Minuten ab.",
      "Nach Ablauf wird die Supabase-Session geloescht und der Login neu verlangt.",
      "2FA muss nach dem neuen Login erneut bestaetigt werden.",
    ],
    title: "Session-Limit auf 45 Minuten",
    type: "fix",
    version: "0.9.3",
  },
  {
    date: "09.06.2026",
    id: "member-case-list-load-limit",
    items: [
      "Mitgliederkartei laedt jetzt bis zu 1000 Akten statt nur die neuesten 50.",
      "Vorhandene Discord-Akten wie Marcel / 777 fallen dadurch nicht mehr aus der sichtbaren Liste.",
      "Datenbankabgleich bestaetigt: Marcel / 777 ist als Akte vorhanden und auf dem Server markiert.",
    ],
    title: "Alle Mitgliederakten sichtbar",
    type: "fix",
    version: "0.9.2",
  },
  {
    date: "09.06.2026",
    id: "member-cases-preserve-off-server",
    items: [
      "Discord-Leave, Kick und Ban loeschen keine Mitgliederakten mehr.",
      "Betroffene Akten werden nur als Nicht auf Server markiert.",
      "Rollen, Dateien, Strafen, Notizen und sonstige Akteninhalte bleiben erhalten.",
      "Live-Event und Vollabgleich ueberschreiben manuell gepflegte Aktenfelder nicht mehr.",
    ],
    title: "Akten bleiben nach Discord-Abgang erhalten",
    type: "fix",
    version: "0.9.1",
  },
  {
    date: "09.06.2026",
    id: "patchnotes-layer",
    items: [
      "Eigenes Patchnotes-Layer in der oberen Leiste ergaenzt.",
      "Patchnotes zentral als App-Daten abgelegt, damit neue Anpassungen ab jetzt sauber mitgeschrieben werden.",
      "Patchnotes bewusst nicht als neue Hauptseite oder Dashboard-Kachel umgesetzt.",
    ],
    title: "Patchnotes eingefuehrt",
    type: "feature",
    version: "0.9.0",
  },
  {
    date: "09.06.2026",
    id: "member-case-reason-dialog",
    items: [
      "Oeffnen-Button in der Mitgliederkartei ist direkt klickbar.",
      "Zugriffsgrund wird jetzt in einem Dialog abgefragt.",
      "Akte oeffnet erst nach Bestaetigung und wird weiterhin protokolliert.",
    ],
    title: "Akten oeffnen per Grund-Dialog",
    type: "feature",
    version: "0.8.3",
  },
  {
    date: "09.06.2026",
    id: "file-actions",
    items: [
      "Verknuepfte Dateien in Akten koennen direkt geoeffnet werden.",
      "Dateien koennen in der Datei-Datenbank verschoben werden.",
      "Dateien koennen aus Datenbank und Supabase Storage geloescht werden.",
      "Direktes Oeffnen laeuft ueber geschuetzte, kurz gueltige Supabase-Links ohne App-Vorschau.",
    ],
    title: "Dateien oeffnen, verschieben und loeschen",
    type: "feature",
    version: "0.8.2",
  },
  {
    date: "09.06.2026",
    id: "auth-mfa-case-view",
    items: [
      "E-Mail-Bestaetigungslinks nutzen die produktive Schland-Adresse statt localhost.",
      "2FA-QR-Code zeigt Schland DB als Namen statt localhost.",
      "Aktendetails sind von der Mitgliederkartei getrennt.",
      "Discord-Benutzername und Discord-Anzeigename werden in Akten getrennt angezeigt.",
    ],
    title: "Login, 2FA und Aktenansicht bereinigt",
    type: "fix",
    version: "0.8.1",
  },
  {
    date: "09.06.2026",
    id: "discord-username-sync",
    items: [
      "Discord-Sync schreibt den echten Benutzernamen bevorzugt vor dem Anzeigenamen.",
      "Railway-Bot und Vercel-Rest-Sync nutzen dieselbe Reihenfolge.",
    ],
    title: "Discordnamen-Sync korrigiert",
    type: "fix",
    version: "0.8.0",
  },
];
